repos:
  - repo: local
    hooks:
      - id: cleanup.sh
        name: cleanup.sh
        entry: scripts/cleanup.sh
        language: script
        pass_filenames: false

      - id: proof.sh
        name: proof.sh
        entry: scripts/proof.sh
        language: script
        pass_filenames: false

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
