name: random number generator

on:
    workflow_dispatch:

jobs:
    generate-random-number:
        runs-on: ubuntu-latest
        outputs:
            number: ${{ steps.generate-number.outputs.number }}
            is-even: ${{ steps.is-even.outputs.is-even }}
        steps:
            - id: generate-number
              run: echo "number=$(echo $RANDOM)" >> "$GITHUB_OUTPUT"
            - id: is-even
              run: |
                echo "is-even=$((${{steps.generate-number.outputs.number}} % 2 == 0))" >> "$GITHUB_OUTPUT"
                echo "The number is ${{steps.generate-number.outputs.number}}" >> $GITHUB_STEP_SUMMARY
